name = "zod-experiments"
main = "src/index.ts"
compatibility_date = "2022-12-01"

[vars]
JWT_SECRET = "secret"
JWT_EXPIRES_IN = "7"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blog"
database_id = "c0bf7406-85d0-40ba-8443-ad85199225df"
preview_database_id = "c0bf7406-85d0-40ba-8443-ad85199225df"
